from .action_only import (
    ActionOnlyFiniteBandit,
    identified_interventional_effect_from_baseline,
    identified_interventional_influence_from_baseline,
    identified_psi_from_baseline,
)
from .bandits import (
    TwoArmedBernoulliBandit,
    closed_form_expected_replay_influence,
    closed_form_interventional_influence,
    compare_local_replay_interventional,
    find_strong_separation_example,
    target_better_arm_probability,
    two_step_positive_prefix,
)
from .core import (
    ComparisonReport,
    FiniteAdaptiveModel,
    GapReport,
    HistoryOutcome,
    compute_expected_replay_effect,
    compute_expected_replay_influence,
    compute_interventional_effect,
    compute_interventional_influence,
    compute_k_prefix_effect,
    compute_k_prefix_influence,
    compute_k_prefix_psi,
    compute_local_next_state_effect,
    compute_psi,
    compute_replay_effect_on_log,
    compute_replay_influence_on_log,
    conditioning_ladder_table,
    one_coordinate_weights,
)
from .differentiable import (
    DifferentiableFiniteAdaptiveModel,
    build_recursion_bundle,
    compute_future_law_score_on_log,
    compute_model_based_interventional_influence,
    compute_score_representation_gap,
    conditioned_stagewise_gap_terms,
)
from .examples import (
    collect_prefixes,
    make_action_only_example,
    make_exogenous_binary_model,
    make_reference_bandit,
    make_two_step_bandit_strong_separation,
    prefix_to_str,
)
from .theorem_checks import (
    conditioning_ladder_report,
    identification_frontier_report,
    paper_claim_check_report,
    recursion_validation_report,
    replay_oracle_insufficiency_report,
)

__all__ = [
    "ActionOnlyFiniteBandit",
    "ComparisonReport",
    "DifferentiableFiniteAdaptiveModel",
    "FiniteAdaptiveModel",
    "GapReport",
    "HistoryOutcome",
    "TwoArmedBernoulliBandit",
    "closed_form_expected_replay_influence",
    "closed_form_interventional_influence",
    "collect_prefixes",
    "compare_local_replay_interventional",
    "compute_expected_replay_effect",
    "compute_expected_replay_influence",
    "compute_future_law_score_on_log",
    "compute_interventional_effect",
    "compute_interventional_influence",
    "compute_k_prefix_effect",
    "compute_k_prefix_influence",
    "compute_k_prefix_psi",
    "compute_local_next_state_effect",
    "compute_model_based_interventional_influence",
    "compute_psi",
    "compute_replay_effect_on_log",
    "compute_replay_influence_on_log",
    "compute_score_representation_gap",
    "conditioning_ladder_report",
    "conditioning_ladder_table",
    "conditioned_stagewise_gap_terms",
    "find_strong_separation_example",
    "identified_interventional_effect_from_baseline",
    "identified_interventional_influence_from_baseline",
    "identified_psi_from_baseline",
    "identification_frontier_report",
    "make_action_only_example",
    "make_exogenous_binary_model",
    "make_reference_bandit",
    "make_two_step_bandit_strong_separation",
    "one_coordinate_weights",
    "paper_claim_check_report",
    "prefix_to_str",
    "build_recursion_bundle",
    "recursion_validation_report",
    "replay_oracle_insufficiency_report",
    "target_better_arm_probability",
    "two_step_positive_prefix",
]

try:
    from .experiments import (
        bandit_gap_scaling_sweep,
        bandit_mu0_sweep,
        bandit_score_gap_summary,
        bandit_stagewise_gap_table,
        effect_curve_over_epsilon,
        full_history_table,
        identification_curve,
        notebook_comparison_summary,
        prefix_gap_table,
    )
    from .plotting import PALETTE, configure_notebook_style, finalise_axes, save_figure_bundle

    __all__ += [
        "PALETTE",
        "bandit_gap_scaling_sweep",
        "bandit_mu0_sweep",
        "bandit_score_gap_summary",
        "bandit_stagewise_gap_table",
        "configure_notebook_style",
        "effect_curve_over_epsilon",
        "finalise_axes",
        "full_history_table",
        "identification_curve",
        "notebook_comparison_summary",
        "prefix_gap_table",
        "save_figure_bundle",
    ]
except ModuleNotFoundError:
    pass

try:
    from .approx import (
        ApproxCurriculumManifest,
        ApproxDependencyError,
        LookaheadSpec,
        OccurrenceScoreRow,
        PpoLiteConfig,
        ReplayLooResult,
        TrainOccurrenceRef,
        alignment_metrics_from_rows,
        collect_cached_curriculum,
        compare_occurrence_scores,
        compute_exact_replay_loo,
        compute_local_snapshot_tracin,
        compute_nonlocal_replay_tracin,
        compute_recollected_occurrence_effect,
        evaluate_policy_return,
        list_occurrences,
        load_buffer,
        pearson_correlation,
        rows_to_table,
        sign_agreement,
        spearman_rank_correlation,
        summarize_by_keys,
        summarize_sweep_runs,
        top_k_overlap,
    )

    __all__ += [
        "ApproxCurriculumManifest",
        "ApproxDependencyError",
        "LookaheadSpec",
        "OccurrenceScoreRow",
        "PpoLiteConfig",
        "ReplayLooResult",
        "TrainOccurrenceRef",
        "alignment_metrics_from_rows",
        "collect_cached_curriculum",
        "compare_occurrence_scores",
        "compute_exact_replay_loo",
        "compute_local_snapshot_tracin",
        "compute_nonlocal_replay_tracin",
        "compute_recollected_occurrence_effect",
        "evaluate_policy_return",
        "list_occurrences",
        "load_buffer",
        "pearson_correlation",
        "rows_to_table",
        "sign_agreement",
        "spearman_rank_correlation",
        "summarize_by_keys",
        "summarize_sweep_runs",
        "top_k_overlap",
    ]
except ModuleNotFoundError:
    pass
